# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-30 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pubisher', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
